image: maven:3.8.5-openjdk-18
# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
stages:
  - build
  - deploy
cache:
  paths:
    - .m2/repository
    - ./target
build:
  image: maven:3.8.5-openjdk-17
  stage: build
  artifacts:
    when: always
    paths:
      - ./target/*.jar
      - Dockerfile
  script:
    - 'mvn package'
    - echo "Hello, you are at build stage."
  only:
    - master (or master)
deploy:docker:	
  image: docker
  services:
    - "docker:dind"
  stage: deploy
  when: manual
  before_script:
    - docker login -u $DOCKER_HUB_USERID -p $DOCKER_HUB_PASSWORD
  script:
    - docker build -t myspringweb .
    - docker tag myspringweb $DOCKER_HUB_USERID/myspringweb
    - docker push $DOCKER_HUB_USERID/myspringweb
  after_script:
    - docker logout
  only:
    - main (or master)
